experimment: 'Fixmatch Gated SSL Cifar10'

# save
save_name: fmgssl_12


# training and fixmatch 

# Gated SSL
arch: Moe1 # Moe1, Lorot, Nomoe
ssl_ratio: 0.1

# optimizer

# dataset
num_workers: 2

# model

# gpu
seed: 6
